version: '3.1'

services:

  server:
    build: ./server/
    restart: unless-stopped
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 8080:8080
    networks:
      graphql:

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db
    networks:
      graphql:

networks:
  graphql: